-- 코드를 입력하세요
SELECT CART_ID
FROM (
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
) AS N
WHERE CART_ID IN(
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
)
ORDER BY CART_ID;