-- 코드를 작성해주세요
-- 3세대 대장균의 ID를 오름차순으로 출력

SELECT THIRD.ID
FROM ECOLI_DATA THIRD
    JOIN ECOLI_DATA SECOND
        ON THIRD.PARENT_ID = SECOND.ID
    JOIN ECOLI_DATA FIRST
        ON SECOND.PARENT_ID = FIRST.ID
WHERE FIRST.ID IS NOT NULL AND FIRST.PARENT_ID IS NULL
        