-- 코드를 입력하세요
-- CAR_RENTAL_COMPANY_CAR: CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY: HISTORY_ID, CAR_ID, START_DATE, END_DATE
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN: PLAN_ID, CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
-- 자동차 종류가 세단이나 SUV인 자동차 중 2022년 11월 1일~11월 30일까지 대여 가능하고 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해 자동차 ID, 자동차 종류, 대여 금액(FEE) 리스트를 대여 금액 내림차순, 자동차 종류 오름차순, 자동차 ID 내림차순 정렬

SELECT CC.CAR_ID, CC.CAR_TYPE, FLOOR(CC.DAILY_FEE * 30 * (1 - CP.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP
        ON CC.CAR_TYPE = CP.CAR_TYPE
        AND CP.DURATION_TYPE = '30일 이상'
WHERE CC.CAR_TYPE IN('세단', 'SUV')
    AND CC.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    AND FLOOR(CC.DAILY_FEE * 30 * (1 - CP.DISCOUNT_RATE / 100)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CC.CAR_TYPE, CC.CAR_ID DESC;
#     JOIN (
#         SELECT HISTORY_ID, CAR_ID, START_DATE, END_DATE
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     ) AS CH
#         ON CH.CAR_ID = CC.CAR_ID
#     LEFT JOIN (
#         SELECT
#             CAR_TYPE,
#             SUBSTRING_INDEX(DURATION_TYPE, '일', 1) AS DURATION_DATE,
#             CAST(SUBSTRING_INDEX(DISCOUNT_RATE, '%', 1) AS SIGNED) AS DISCOUNT_RATE
#         FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#     ) AS CP
#         ON CC.CAR_TYPE = CP.CAR_TYPE AND CP.DURATION_DATE = 30
#         # CH.RENT_DATE > CP.DURATION_DATE AND CP.CAR_TYPE = '트럭'
# WHERE CC.CAR_TYPE IN('세단', 'SUV') AND DATE_FORMAT(END_DATE, '%Y-%m-%d') < '2022-11-01' AND FLOOR(CC.DAILY_FEE * 30 * (1 - CP.DISCOUNT_RATE / 100)) BETWEEN 500000 AND 1999999
# # GROUP BY CC.CAR_ID
# ORDER BY FEE DESC, CC.CAR_TYPE, CC.CAR_ID DESC;
