-- 코드를 입력하세요
# 이 코드도 결과가 같은데 왜 안되지?
# SELECT P.PRODUCT_ID, P.PRODUCT_NAME, O.TOTAL_SALES
# FROM FOOD_PRODUCT P
#     LEFT JOIN (
#         SELECT
#             O.PRODUCT_ID,
#             O.PRODUCE_DATE,
#             SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
#         FROM FOOD_PRODUCT P
#             LEFT JOIN FOOD_ORDER O
#             ON P.PRODUCT_ID = O.PRODUCT_ID
#         GROUP BY P.PRODUCT_ID
#     ) AS O
#     ON P.PRODUCT_ID = O.PRODUCT_ID
# WHERE DATE_FORMAT(O.PRODUCE_DATE, '%Y-%m') = '2022-05'
# ORDER BY O.TOTAL_SALES DESC, P.PRODUCT_ID;

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
    LEFT JOIN FOOD_ORDER O
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE DATE_FORMAT(O.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;