-- 코드를 입력하세요
-- CAR_RENTAL_COMPANY_CAR: 대여 중인 자동차들의 정보를 담은 테이블
    -- 자동차 종류: '세단', 'SUV', '승합차', '트럭', '리무진'
    -- 자동차 옵션 리스트: 주차감지센서', '스마트키', '네비게이션', '통풍시트', '열선시트', '후방카메라', '가죽시트'
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY: 자동차 대여 기록 정보를 담은 테이블
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN: 자동차 종류 별 대여 기간 종류 별 할인 정책 정보를 담은 테이블
    -- 할인율이 적용되는 대여 기간 종류: 7일, 30일, 90일 이상

-- 자동차 종류가 트럭인 자동차의 대여 기록에 대해 대여 기록 별로 대여 금액(컬럼명: FEE)을 구해 대여 기록 ID, 대여 금액 리스트 출력
-- 금액 내림차순, 기록 ID 내림차순 정렬
-- FEE 컬럼은 정수부분만 출력

-- 할인된 금액을 구한 뒤 * 빌린 날짜
-- DATEDIFF(CRH.END_DATE, CRH.START_DATE)
# SELECT CRH.HISTORY_ID, (
#     CASE
#         WHEN DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 7 THEN ROUND(CRC.DAILY_FEE * 0.05 * DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1, 0)
#         WHEN DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 30 THEN ROUND(CRC.DAILY_FEE * 0.07 * DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1, 0)
#         WHEN DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 90 THEN ROUND(CRC.DAILY_FEE * 0.1 * DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1, 0)
#         ELSE ROUND(CRC.DAILY_FEE * DATEDIFF(CRH.END_DATE, CRH.START_DATE), 0)
#     END
# ) AS FEE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRH
#     JOIN CAR_RENTAL_COMPANY_CAR CRC
#     ON CRH.CAR_ID = CRC.CAR_ID
# WHERE CRC.CAR_TYPE = '트럭'
# ORDER BY FEE DESC, HISTORY_ID DESC;

-- 높은 값을 쓰고 DURATION_RATE가 NULL이면 그냥 1
SELECT HISTORY_ID, ROUND((DAILY_FEE * RENT_DATE) - (DAILY_FEE * RENT_DATE * IFNULL(MAX(DISCOUNT_RATE), 0) * 0.01)) AS FEE
# ROUND(DAILY_FEE * IFNULL(MAX(DISCOUNT_RATE) * 0.01, 1) * RENT_DATE) AS FEE, DAILY_FEE, RENT_DATE, DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_CAR CRC
    JOIN (
        SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS RENT_DATE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) AS CRH
        ON CRH.CAR_ID = CRC.CAR_ID
    LEFT JOIN (
        SELECT
            CAR_TYPE,
            SUBSTRING_INDEX(DURATION_TYPE, '일', 1) AS DURATION_DATE,
            CAST(SUBSTRING_INDEX(DISCOUNT_RATE, '%', 1) AS SIGNED) AS DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    ) AS CRDP
        ON CRH.RENT_DATE > CRDP.DURATION_DATE AND CRDP.CAR_TYPE = '트럭'
WHERE CRC.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID -- CRDP 테이블을 JOIN하는 조건문이 충족되면 여러 DURATION_RATE가 들어가므로 묶은 후 가장 큰 값으로 COLUMN을 선택해야함
ORDER BY FEE DESC, HISTORY_ID DESC;