-- 코드를 입력하세요
-- 0~23시까지 각 시간대별로 입양이 몇 건 발생했는지 시간대 순으로 조회

WITH RECURSIVE TIMETABLE AS (
    SELECT 0 AS HOUR
    UNION
    SELECT HOUR + 1
    FROM TIMETABLE
    WHERE HOUR < 23
)

SELECT HOUR, COUNT(AO.ANIMAL_ID) AS COUNT
FROM TIMETABLE T
    LEFT JOIN ANIMAL_OUTS AO
    ON T.HOUR = HOUR(AO.DATETIME)
GROUP BY HOUR
ORDER BY HOUR