-- 코드를 작성해주세요
SELECT S.SCORE, S.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM
    (
        SELECT EMP_NO, SUM(SCORE) AS SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) S
    JOIN HR_EMPLOYEES E
    ON S.EMP_NO = E.EMP_NO
WHERE S.SCORE IN(
    SELECT MAX(M.SCORE)
    FROM
        (
            SELECT SUM(SCORE) AS SCORE
            FROM HR_GRADE
            GROUP BY EMP_NO
        ) M
    )